### ISSUE TITLE
Calling Simplecov.start more than once raises an exception

### ISSUE THREAD

**Issue by dillonwelch** [colszowka/simplecov#1003]
It looks like `ruby-head` made an [update](https://github.com/ruby/ruby/pull/4856/files#diff-4fd3567b713b460fa5616259e35ab22faaa28376ea929ce0254744d6e16ffd33R78) a few days ago that caused `Coverage.start` to raise an exception if you call it more than once. Naturally, this will also cause `SimpleCov.start` to raise the same exception.

[Here](https://github.com/devise-security/devise-security/runs/4036725052?check_suite_focus=true) is an example of what happens:

```
Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected
/home/runner/work/devise-security/devise-security/gemfiles/vendor/bundle/ruby/3.1.0/gems/simplecov-0.21.2/lib/simplecov.rb:354:in `start': coverage measurement is already setup (RuntimeError)
	from /home/runner/work/devise-security/devise-security/gemfiles/vendor/bundle/ruby/3.1.0/gems/simplecov-0.21.2/lib/simplecov.rb:354:in `start_coverage_with_criteria'
	from /home/runner/work/devise-security/devise-security/gemfiles/vendor/bundle/ruby/3.1.0/gems/simplecov-0.21.2/lib/simplecov.rb:343:in `start_coverage_measurement'
	from /home/runner/work/devise-security/devise-security/gemfiles/vendor/bundle/ruby/3.1.0/gems/simplecov-0.21.2/lib/simplecov.rb:59:in `start'
	from /home/runner/work/devise-security/devise-security/test/test_helper.rb:26:in `<top (required)>'
	from /home/runner/work/devise-security/devise-security/test/test_compatibility.rb:3:in `require'
	from /home/runner/work/devise-security/devise-security/test/test_compatibility.rb:3:in `<top (required)>'
	from /home/runner/work/devise-security/devise-security/gemfiles/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:21:in `require'
	from /home/runner/work/devise-security/devise-security/gemfiles/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:21:in `block in <main>'
	from /home/runner/work/devise-security/devise-security/gemfiles/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `select'
	from /home/runner/work/devise-security/devise-security/gemfiles/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `<main>'
```

You can see at https://github.com/devise-security/devise-security/pull/343 where the issue was fixed once I updated to only do this once.

Is there a way that SimpleCov can wrap this into something more presentable so that the fix is clear? It took me digging into the ruby source code to figure out why it only failed in Ruby 3.1 (aka ruby-head)

Also, the [unstable](https://github.com/simplecov-ruby/simplecov/actions/workflows/unstable.yml) tests on this repo appear to be failing? Doesn't seem related based on the error but I figure I'd point it out.

**Comment by luke-hill** [comment]
I only call Simplecov.start once in my CI, but it seems to still throw this error. I just added 3.1 to my run matrix.

See https://github.com/site-prism/site_prism/actions/runs/3337538167/jobs/5524008967

I "do" require simplecov in 2 diff places (rspec and cucumber), but this is just for redundancy I believed.

**Comment by yegor256** [comment]
Any update on this? I experience the same problem with Ruby 3.2.1.

**Comment by senemsoy** [comment]
I'm also experiencing the same problem with Ruby `3.1.4`

**Comment by nicolaep** [comment]
Face it with Ruby 3.1.4 on version (0.21.2)
Upgrading to simplecov (0.22.0) solved it

**Comment by mykhi** [comment]
I can confirm that upgrading to `0.22.0` solves it, so this issue could be probably be closed.

**Comment by esposito** [comment]
I'm still having this issue on 0.22.0

**Comment by sferik** [comment]
`SimpleCov.start` is now idempotent. This was resolved by [1cc7650454fc7c53e7a724941662c3e9d3329ccc](https://github.com/simplecov-ruby/simplecov/commit/1cc7650454fc7c53e7a724941662c3e9d3329ccc)
  (by @mame)  with a follow-up in [0c27173b351aff588cbe7b244e4ffa294edf12d9](https://github.com/simplecov-ruby/simplecov/commit/0c27173b351aff588cbe7b244e4ffa294edf12d9) (by @notEthan) so the guard is safe on runtimes where `Coverage.running?` isn't implemented.

Thanks for the report!
