### ISSUE TITLE
couldn't find HOME environment -- expanding `~' (ArgumentError)

### ISSUE THREAD

**Issue by mhenrixon** [colszowka/simplecov#470]
Hi,

You have the same issue as rubocop did in https://github.com/bbatsov/rubocop/issues/2901 simplecov crash unless a HOME environment variable is defined.

```
/var/lib/gems/2.1.0/gems/simplecov-0.11.2/lib/simplecov/defaults.rb:99:in `expand_path': couldn't find HOME environment -- expanding `~' (ArgumentError)
	from /var/lib/gems/2.1.0/gems/simplecov-0.11.2/lib/simplecov/defaults.rb:99:in `<top (required)>'
	from /var/lib/gems/2.1.0/gems/simplecov-0.11.2/lib/simplecov.rb:180:in `require'
	from /var/lib/gems/2.1.0/gems/simplecov-0.11.2/lib/simplecov.rb:180:in `<top (required)>'
	from /root/.jenkins/jobs/e24-accounting/workspace/spec/spec_helper.rb:5:in `require'
	from /root/.jenkins/jobs/e24-accounting/workspace/spec/spec_helper.rb:5:in `<top (required)>'
	from /root/.jenkins/jobs/e24-accounting/workspace/spec/features/bitcoin_deposit_obsoletes_deposit_address_spec.rb:1:in `require'
	from /root/.jenkins/jobs/e24-accounting/workspace/spec/features/bitcoin_deposit_obsoletes_deposit_address_spec.rb:1:in `<top (required)>'
	from /var/lib/gems/2.1.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1361:in `load'
	from /var/lib/gems/2.1.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
	from /var/lib/gems/2.1.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1359:in `each'
	from /var/lib/gems/2.1.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
	from /var/lib/gems/2.1.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:102:in `setup'
	from /var/lib/gems/2.1.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:88:in `run'
	from /var/lib/gems/2.1.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:73:in `run'
	from /var/lib/gems/2.1.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:41:in `invoke'
	from /var/lib/gems/2.1.0/gems/rspec-core-3.4.1/exe/rspec:4:in `<main>'
/usr/bin/ruby2.1 -I/var/lib/gems/2.1.0/gems/rspec-core-3.4.1/lib:/var/lib/gems/2.1.0/gems/rspec-support-3.4.1/lib /var/lib/gems/2.1.0/gems/rspec-core-3.4.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

**Comment by hube** [comment]
I just encountered the same issue. It looks like this was originally fixed in #311, but then re-introduced in 9afdb46f5f15ec8ddf79fb915d4bb27b4821bea8. One workaround would be to revert to using v0.9 until this gets merged

**Comment by hube** [comment]
Thanks for merging the fix in!
