### ISSUE TITLE
CircleCI: invalid byte sequence in UTF-8 (ArgumentError)

### ISSUE THREAD

**Issue by joshuamcginnis** [colszowka/simplecov#655]
I'm getting the following error *only* when running rspec in CircleCI environment. The same command works fine on our local environments.

I'm using `ruby 2.5.0` and `simplecov 0.15.1`.

```ruby
# /spec/spec_helper.rb
require 'simplecov'

# save to CircleCI's artifacts directory if we're on CircleCI
if ENV['CIRCLE_ARTIFACTS']
  dir = File.join(ENV['CIRCLE_ARTIFACTS'], 'coverage')
  SimpleCov.coverage_dir(dir)
end

SimpleCov.start
```

**Failure Message**
```bash
Finished in 0.36838 seconds (files took 3.18 seconds to load)
32 examples, 0 failures

Traceback (most recent call last):
	11: from /home/ubuntu/darwin/vendor/bundle/ruby/2.5.0/gems/simplecov-0.15.1/lib/simplecov/defaults.rb:68:in `block in <top (required)>'
	10: from /home/ubuntu/darwin/vendor/bundle/ruby/2.5.0/gems/simplecov-0.15.1/lib/simplecov/configuration.rb:180:in `block in at_exit'
	 9: from /home/ubuntu/darwin/vendor/bundle/ruby/2.5.0/gems/simplecov-0.15.1/lib/simplecov.rb:82:in `result'
	 8: from /home/ubuntu/darwin/vendor/bundle/ruby/2.5.0/gems/simplecov-0.15.1/lib/simplecov.rb:63:in `add_not_loaded_files'
	 7: from /home/ubuntu/darwin/vendor/bundle/ruby/2.5.0/gems/simplecov-0.15.1/lib/simplecov.rb:63:in `each'
	 6: from /home/ubuntu/darwin/vendor/bundle/ruby/2.5.0/gems/simplecov-0.15.1/lib/simplecov.rb:66:in `block in add_not_loaded_files'
	 5: from /home/ubuntu/darwin/vendor/bundle/ruby/2.5.0/gems/simplecov-0.15.1/lib/simplecov/lines_classifier.rb:20:in `classify'
	 4: from /home/ubuntu/darwin/vendor/bundle/ruby/2.5.0/gems/simplecov-0.15.1/lib/simplecov/lines_classifier.rb:20:in `map'
	 3: from /home/ubuntu/darwin/vendor/bundle/ruby/2.5.0/gems/simplecov-0.15.1/lib/simplecov/lines_classifier.rb:20:in `each'
	 2: from /home/ubuntu/darwin/vendor/bundle/ruby/2.5.0/gems/simplecov-0.15.1/lib/simplecov/lines_classifier.rb:20:in `foreach'
	 1: from /home/ubuntu/darwin/vendor/bundle/ruby/2.5.0/gems/simplecov-0.15.1/lib/simplecov/lines_classifier.rb:21:in `block in classify'
/home/ubuntu/darwin/vendor/bundle/ruby/2.5.0/gems/simplecov-0.15.1/lib/simplecov/lines_classifier.rb:21:in `=~': invalid byte sequence in UTF-8 (ArgumentError)

bundle exec rspec --require spec_helper spec --format documentation returned exit code 1
```

Do you have any ideas on how to appropriately troubleshoot this error?

**Comment by thesmart** [comment]
I'm getting this same error and have noticed that it has something to do with UTF-8 characters in some source files.  I think simplecov is opening files in ascii text mode?

**Comment by PragTob** [comment]
:wave:

Hi, I think the offending line is [this one](https://github.com/colszowka/simplecov/blob/master/lib/simplecov/lines_classifier.rb#L23).

` if line =~ self.class.no_cov_line `

So, something is wrong with that line or how simplecov is. Printing out the line that fails would be helpful and would help us create a test case either for line classifier or more integrationy including the file loading to make that pass.

**Comment by joshuamcginnis** [comment]
While this doesn't address the issue of the `ñ`, I realized that by activating the built-in `rails` profile, the issue goes away as it doesn't cover the offending file in the vendor folder: 

`Simplecov.start 'rails'`

**Comment by PragTob** [comment]
Hi there,

`add_filter` should work in general I don't know why it wouldn't. Unless you use something like `track_files` or so that overrides the filtering iirc. An example repo would be nice but afaik it works?

We probably also shouldn't bundle up our spec fixtures so removing those might also help :D

**Comment by PragTob** [comment]
Updated to highlight what one of the root causes here seems to be

**Comment by sferik** [comment]
Thanks for reporting this issue. I’ve spent some time looking into it and I’m fairly confident it’s fixed!

The original crash (`invalid byte sequence in UTF-8` from `LinesClassifier`) was fixed in 67bd66a52706976eadb7b53a4af5d2e938e0a9d0 and refined in e26ae2f69b302c72901b0f95720de5fb4f77085f, which added guards so invalid byte sequences are treated as relevant lines instead of crashing.

The packaging issue that exposed SimpleCov’s fixtures was addressed in 1378af69dacd485920235c50305de483818320f2`, which stopped shipping specs/cukes in the gem.

Regression coverage is in `spec/lines_classifier_spec.rb` for invalid UTF-8 byte sequences, with broader source-encoding coverage in `spec/source_file_spec.rb` and `features/encoding.feature`.

If the issue reoccurs, please reopen it (or open a new one). Thanks again!
