### ISSUE TITLE
Flaky Cucumber Feature(s) unter JRuby on Travis

### ISSUE THREAD

**Issue by PragTob** [colszowka/simplecov#776]
```
/home/travis/.rvm/rubies/jruby-9.2.9.0/bin/jruby -S bundle exec cucumber

Using the default profile...

..................................................................................F-......................................................................................................................................................................................................

(::) failed steps (::)

No such file or directory - No such file or directory - /home/travis/build/colszowka/simplecov/features/support/../../tmp/aruba/project/coverage/assets/0.10.2/loading.gif (Errno::ENOENT)

./features/support/env.rb:18:in `block in <main>'

features/config_project_name.feature:26:in `When I open the coverage report generated with `bundle exec rake test`'

Failing Scenarios:

cucumber features/config_project_name.feature:19 # Scenario: Custom name
```

What to do? Find out why and fix it :)

**Comment by PragTob** [comment]
/home/travis/.rvm/rubies/jruby-9.2.9.0/bin/jruby -S bundle exec cucumber

Using the default profile...

..................................................................................F-...................................................................................................................................................................................................................

(::) failed steps (::)

No such file or directory - No such file or directory - /home/travis/build/colszowka/simplecov/features/support/../../tmp/aruba/project/coverage/assets/0.10.2/loading.gif (Errno::ENOENT)

./features/support/env.rb:17:in `block in ./features/support/env.rb'

features/config_project_name.feature:26:in `When I open the coverage report generated with `bundle exec rake test`'

Failing Scenarios:

cucumber features/config_project_name.feature:19 # Scenario: Custom name

55 scenarios (1 failed, 54 passed)

295 steps (1 failed, 1 skipped, 293 passed)

9m40.710s

The command "bundle exec rake" exited with 1.
