### ISSUE TITLE
Problem with loading Minitest simplecov plugin

### ISSUE THREAD

**Issue by edariedl** [colszowka/simplecov#877]
Hi,

I've just updated simplecov to the latest version 0.18.4 in our Rails app (Rails 6.0.2.1 with Minitest 5.14.0, Ruby 2.6.5). We are not loading simplcov every time, but we use the ENV variable to turn it on.

Gemfile configuration:
```ruby
group :test do
  gem 'simplecov', require: false
end
```

At the top of our `test_helper.rb`:
```ruby
if ENV["COVERAGE"]
  require 'simplecov'
  SimpleCov.coverage_dir(File.join("..", "..", "..", ENV['CIRCLE_ARTIFACTS'], "coverage")) if ENV['CIRCLE_ARTIFACTS']
  SimpleCov.start 'rails'
end
```

When I run the tests without `COVERAGE` env variable I get following error:
```
→ rails test
Running via Spring preloader in process 44891
Traceback (most recent call last):
	14: from -e:1:in `<main>'
	13: from /Users/edariedl/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	12: from /Users/edariedl/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /Users/edariedl/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/application/boot.rb:19:in `<top (required)>'
	10: from /Users/edariedl/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/application.rb:139:in `run'
	 9: from /Users/edariedl/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/application.rb:139:in `loop'
	 8: from /Users/edariedl/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/application.rb:145:in `block in run'
	 7: from /Users/edariedl/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/application.rb:175:in `serve'
	 6: from /Users/edariedl/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/application.rb:175:in `fork'
	 5: from /Users/edariedl/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.14.0/lib/minitest.rb:68:in `block in autorun'
	 4: from /Users/edariedl/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.14.0/lib/minitest.rb:135:in `run'
	 3: from /Users/edariedl/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.14.0/lib/minitest.rb:84:in `init_plugins'
	 2: from /Users/edariedl/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.14.0/lib/minitest.rb:84:in `each'
	 1: from /Users/edariedl/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.14.0/lib/minitest.rb:86:in `block in init_plugins'
/Users/edariedl/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/simplecov-0.18.4/lib/minitest/simplecov_plugin.rb:7:in `plugin_simplecov_init': uninitialized constant Minitest::SimpleCov (NameError)
Did you mean?  SimpleDelegator
```

I looked into it a bit, and unfortunately Minitest is [loading plugins](https://github.com/seattlerb/minitest/blob/v5.14.0/lib/minitest.rb#L90) via `Gem.find_files("minitest/*_plugin.rb")` and it loads plugin files for every gem in the Gemfile even if it is not required in the projetct at a time.

I tried to test it in the rails console. First I made sure that simplecov is not required and then I tried to run the `Gem.find_files("minitest/*_plugin.rb")`. As you can see `minitest/simplecov_plugin.rb` was found anyway:
```
irb(main):002:0> defined?(SimpleCov)
=> nil
irb(main):003:0> Gem.find_files("minitest/*_plugin.rb").each do |plugin_path|
irb(main):004:1*   puts plugin_path
irb(main):005:1> end; nil
/Users/edariedl/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/simplecov-0.18.4/lib/minitest/simplecov_plugin.rb
/Users/edariedl/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/minitest/rails_plugin.rb
/Users/edariedl/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.14.0/lib/minitest/pride_plugin.rb
=> nil
```
Thanks!

**Comment by PragTob** [comment]
That behavior from `minitest` is... interesting. Thanks for the report!

I see, I'll make it x days in a row with a bugfix release I guess.

I guess wrapping the code we want to trigger in `if defined?(SimpleCov)` should solve this, right?

And the scenario is a project with minitest running tests without requiring `SimpleCov`. A fun scenario to include in the test suite for SimpleCov :grin:

**Comment by edariedl** [comment]
Yeah, it is pretty fun behaviour from `minitest` :)

I would hope that wrapping the code in `if defined?(SimpleCov)` could solve it.

**Comment by juandg** [comment]
I'm experiencing the same issue with minitest on the latest version 0.18.4
