### ISSUE TITLE
Fails with JRuby

### ISSUE THREAD

**Issue by AlexWayfer** [colszowka/simplecov#908]
Against this project:

```
> bundle exec rspec
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.headius.backport9.modules.Modules to method sun.nio.ch.NativeThread.signal(long)
WARNING: Please consider reporting this to the maintainers of com.headius.backport9.modules.Modules
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Randomized with seed 27538
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.headius.backport9.modules.Modules to method sun.nio.ch.NativeThread.signal(long)
WARNING: Please consider reporting this to the maintainers of com.headius.backport9.modules.Modules
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Coverage may be inaccurate; set the "--debug" command line option, or do JRUBY_OPTS="--debug" or set the "debug.fullTrace=true" option in your .jrubyrc
/home/alex/Projects/ruby/simplecov/lib/simplecov.rb:344: warning: tracing (e.g. set_trace_func) will not capture all events without --debug flag
..............................................................................................................................................................................................................................................................................................................................FF......FF.F.
Non-app warnings written to tmp/warnings.txt



Failures:

  1) gemspec sanity has no warnings
     Failure/Error: expect(build[1]).not_to include("WARNING")
       expected "WARNING: An illegal reflective access operation has occurred\nWARNING: Illegal reflective access by ...tive access operations\nWARNING: All illegal access operations will be denied in a future release\n" not to include "WARNING"
     # ./spec/gemspec_spec.rb:17:in `block in <main>'

  2) return codes inside fixtures/frameworks when running rspec_bad.rb behaves like bad tests when print_error_status is disabled does not print anything to STDERR
     Failure/Error: expect(@stderr).to be_empty
       expected `"WARNING: An illegal reflective access operation has occurred\nWARNING: Illegal reflective access by ...v.rb:344: warning: tracing (e.g. set_trace_func) will not capture all events without --debug flag\n".empty?` to return true, got false
     Shared Example Group: "bad tests" called from ./spec/return_codes_spec.rb:71
     # ./spec/return_codes_spec.rb:49:in `block in <main>'
     # ./spec/return_codes_spec.rb:12:in `block in <main>'
     # ./spec/return_codes_spec.rb:10:in `block in <main>'

  3) return codes inside fixtures/frameworks when running testunit_bad.rb behaves like bad tests when print_error_status is disabled does not print anything to STDERR
     Failure/Error: expect(@stderr).to be_empty
       expected `"WARNING: An illegal reflective access operation has occurred\nWARNING: Illegal reflective access by ...ert.rb:8: warning: tracing (e.g. set_trace_func) will not capture all events without --debug flag\n".empty?` to return true, got false
     Shared Example Group: "bad tests" called from ./spec/return_codes_spec.rb:66
     # ./spec/return_codes_spec.rb:49:in `block in <main>'
     # ./spec/return_codes_spec.rb:12:in `block in <main>'
     # ./spec/return_codes_spec.rb:10:in `block in <main>'

  4) return codes inside fixtures/frameworks when running testunit_good.rb behaves like good tests prints nothing to STDERR
     Failure/Error: expect(@stderr).to be_empty
       expected `"WARNING: An illegal reflective access operation has occurred\nWARNING: Illegal reflective access by ...ert.rb:8: warning: tracing (e.g. set_trace_func) will not capture all events without --debug flag\n".empty?` to return true, got false
     Shared Example Group: "good tests" called from ./spec/return_codes_spec.rb:56
     # ./spec/return_codes_spec.rb:26:in `block in <main>'
     # ./spec/return_codes_spec.rb:12:in `block in <main>'
     # ./spec/return_codes_spec.rb:10:in `block in <main>'

  5) return codes inside fixtures/frameworks when running rspec_good.rb behaves like good tests prints nothing to STDERR
     Failure/Error: expect(@stderr).to be_empty
       expected `"WARNING: An illegal reflective access operation has occurred\nWARNING: Illegal reflective access by ...v.rb:344: warning: tracing (e.g. set_trace_func) will not capture all events without --debug flag\n".empty?` to return true, got false
     Shared Example Group: "good tests" called from ./spec/return_codes_spec.rb:61
     # ./spec/return_codes_spec.rb:26:in `block in <main>'
     # ./spec/return_codes_spec.rb:12:in `block in <main>'
     # ./spec/return_codes_spec.rb:10:in `block in <main>'

Finished in 50.47 seconds (files took 0.76961 seconds to load)
331 examples, 5 failures

Failed examples:

rspec ./spec/gemspec_spec.rb:16 # gemspec sanity has no warnings
rspec ./spec/return_codes_spec.rb[1:1:4:1:2:2] # return codes inside fixtures/frameworks when running rspec_bad.rb behaves like bad tests when print_error_status is disabled does not print anything to STDERR
rspec ./spec/return_codes_spec.rb[1:1:3:1:2:2] # return codes inside fixtures/frameworks when running testunit_bad.rb behaves like bad tests when print_error_status is disabled does not print anything to STDERR
rspec ./spec/return_codes_spec.rb[1:1:1:1:2] # return codes inside fixtures/frameworks when running testunit_good.rb behaves like good tests prints nothing to STDERR
rspec ./spec/return_codes_spec.rb[1:1:2:1:2] # return codes inside fixtures/frameworks when running rspec_good.rb behaves like good tests prints nothing to STDERR

Randomized with seed 27538
````

I've taken the JRuby version from CI config:

```
> ruby -v
jruby 9.2.11.1 (2.5.7) 2020-03-25 b1f55b1a40 OpenJDK 64-Bit Server VM 14.0.2+12 on 14.0.2+12 +jit [linux-x86_64]
```

**Comment by PragTob** [comment]
:wave: 

Hi there, thanks for the report. These are related to running JRuby with JDK 11+. While we could make our tests aware of these, I'd rather have them fixed upstream in JRuby. I'll report these.

Cheers,
Tobi

**Comment by PragTob** [comment]
Oh and for all but one of these, running with `JRUBY_OPTS=--debug` solves it (as the CI does)

**Comment by AlexWayfer** [comment]
> Oh and for all but one of these, running with `JRUBY_OPTS=--debug` solves it (as the CI does)

It doesn't help:

```
> env JRUBY_OPTS=--debug bundle exec rspec
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.headius.backport9.modules.Modules to method sun.nio.ch.NativeThread.signal(long)
WARNING: Please consider reporting this to the maintainers of com.headius.backport9.modules.Modules
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Randomized with seed 38537
.........................................................................................................................FF..F..F.........................................................................................................................................WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.headius.backport9.modules.Modules to method sun.nio.ch.NativeThread.signal(long)
WARNING: Please consider reporting this to the maintainers of com.headius.backport9.modules.Modules
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
.............................F...................................
Non-app warnings written to tmp/warnings.txt



Failures:

  1) return codes inside fixtures/frameworks when running rspec_good.rb behaves like good tests prints nothing to STDERR
     Failure/Error: expect(@stderr).to be_empty
       expected `"WARNING: An illegal reflective access operation has occurred\nWARNING: Illegal reflective access by ...tive access operations\nWARNING: All illegal access operations will be denied in a future release\n".empty?` to return true, got false
     Shared Example Group: "good tests" called from ./spec/return_codes_spec.rb:61
     # ./spec/return_codes_spec.rb:26:in `block in <main>'
     # ./spec/return_codes_spec.rb:12:in `block in <main>'
     # ./spec/return_codes_spec.rb:10:in `block in <main>'

  2) return codes inside fixtures/frameworks when running testunit_good.rb behaves like good tests prints nothing to STDERR
     Failure/Error: expect(@stderr).to be_empty
       expected `"WARNING: An illegal reflective access operation has occurred\nWARNING: Illegal reflective access by ...tive access operations\nWARNING: All illegal access operations will be denied in a future release\n".empty?` to return true, got false
     Shared Example Group: "good tests" called from ./spec/return_codes_spec.rb:56
     # ./spec/return_codes_spec.rb:26:in `block in <main>'
     # ./spec/return_codes_spec.rb:12:in `block in <main>'
     # ./spec/return_codes_spec.rb:10:in `block in <main>'

  3) return codes inside fixtures/frameworks when running rspec_bad.rb behaves like bad tests when print_error_status is disabled does not print anything to STDERR
     Failure/Error: expect(@stderr).to be_empty
       expected `"WARNING: An illegal reflective access operation has occurred\nWARNING: Illegal reflective access by ...tive access operations\nWARNING: All illegal access operations will be denied in a future release\n".empty?` to return true, got false
     Shared Example Group: "bad tests" called from ./spec/return_codes_spec.rb:71
     # ./spec/return_codes_spec.rb:49:in `block in <main>'
     # ./spec/return_codes_spec.rb:12:in `block in <main>'
     # ./spec/return_codes_spec.rb:10:in `block in <main>'

  4) return codes inside fixtures/frameworks when running testunit_bad.rb behaves like bad tests when print_error_status is disabled does not print anything to STDERR
     Failure/Error: expect(@stderr).to be_empty
       expected `"WARNING: An illegal reflective access operation has occurred\nWARNING: Illegal reflective access by ...tive access operations\nWARNING: All illegal access operations will be denied in a future release\n".empty?` to return true, got false
     Shared Example Group: "bad tests" called from ./spec/return_codes_spec.rb:66
     # ./spec/return_codes_spec.rb:49:in `block in <main>'
     # ./spec/return_codes_spec.rb:12:in `block in <main>'
     # ./spec/return_codes_spec.rb:10:in `block in <main>'

  5) gemspec sanity has no warnings
     Failure/Error: expect(build[1]).not_to include("WARNING")
       expected "WARNING: An illegal reflective access operation has occurred\nWARNING: Illegal reflective access by ...tive access operations\nWARNING: All illegal access operations will be denied in a future release\n" not to include "WARNING"
     # ./spec/gemspec_spec.rb:17:in `block in <main>'

Finished in 57.3 seconds (files took 0.9337 seconds to load)
331 examples, 5 failures

Failed examples:

rspec ./spec/return_codes_spec.rb[1:1:2:1:2] # return codes inside fixtures/frameworks when running rspec_good.rb behaves like good tests prints nothing to STDERR
rspec ./spec/return_codes_spec.rb[1:1:1:1:2] # return codes inside fixtures/frameworks when running testunit_good.rb behaves like good tests prints nothing to STDERR
rspec ./spec/return_codes_spec.rb[1:1:4:1:2:2] # return codes inside fixtures/frameworks when running rspec_bad.rb behaves like bad tests when print_error_status is disabled does not print anything to STDERR
rspec ./spec/return_codes_spec.rb[1:1:3:1:2:2] # return codes inside fixtures/frameworks when running testunit_bad.rb behaves like bad tests when print_error_status is disabled does not print anything to STDERR
rspec ./spec/gemspec_spec.rb:16 # gemspec sanity has no warnings

Randomized with seed 38537
```

(`env` at the beginning of command is necessary for Fish shell)

**Comment by PragTob** [comment]
@AlexWayfer seems like you still get different errors from the ones I was getting in theses tests:

```
  4) return codes inside fixtures/frameworks when running rspec_bad.rb behaves like bad tests when print_error_status is disabled does not print anything to STDERR
     Failure/Error: expect(@stderr).to be_empty
       expected `"Coverage may be inaccurate; set the \"--debug\" command line option, or do JRUBY_OPTS=\"--debug\" or...v.rb:344: warning: tracing (e.g. set_trace_func) will not capture all events without --debug flag\n".empty?` to return true, got false
     Shared Example Group: "bad tests" called from ./spec/return_codes_spec.rb:71
     # ./spec/return_codes_spec.rb:49:in `block in <main>'
```

(when running without the JRUBY_OPTS)

Your warnings are coming from JRuby. Have a look at https://github.com/jruby/jruby/issues/6356 and the issues it references.

If I were to guess I'd say that maybe your `jruby-launcher` is more outdated (the most recent version supposedly fixed things) or something else is going on. You can use the commands described/used in that issue to determine what action is causing the warnings.

Most recent jruby-launcher is 1.1.13.

We could adjust our tests to not trigger on that warning/not run them on JRuby but tbh as long as CI runs I'd rather see them fixed upstream and keep them like this.
